version: "3.8"

services:
    mysql:
        image: mysql:8
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: 123456789
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    nodejs:
        image: 0981987832/wsb:latest
        container_name: nodejs_server
        restart: always
        depends_on:
            - mysql
        ports:
            - "3000:3000"
        environment:
            DATABASE_NAME: "mydb"
            DATABASE_USERNAME: "user"
            DATABASE_PASSWORD: "123456789"
            DATABASE_HOST: "52.63.107.219"
            DATABASE_DIALECT: "mysql"
            DATABASE_PORT: "3306"

            PORT: "3000"

            JWT_SECRET_KEY: "34322342ef"
            JWT_EXPIRES_IN: "1h"
            JWT_EXPIRES_IN_ACCESS_TOKEN: "10h"
            JWT_EXPIRES_IN_REFRESH_TOKEN: "30d"

            DEFAULT_LIMIT_PAGE: "10"
            DEFAULT_PAGE: "1"

            EMAIL_USER: "bcd@gmail.com"
            EMAIL_PASSWORD: "123456789"

    nginx:
        image: nginx:latest
        container_name: nginx_proxy
        restart: always
        depends_on:
            - nodejs
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
    mysql_data:
